services:

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    container_name: app
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - RATE_LIMIT_IP=5
      - RATE_LIMIT_TOKEN=10
      - BLOCK_TIME_IP=300
      - BLOCK_TIME_TOKEN=300
    depends_on:
      - redis
